### ISSUE TITLE
Using min_review_length limits results

### ISSUE THREAD

**Issue by jonathanbossenger** [duplaja/codeable-reviews-and-expert-profile#4]
Using min_review_length=1 only shows 2 of the default 4, I would still expect it to show 4, but merely filter out the ones without reviews.

**Comment by duplaja** [comment]
This one is currently in the works for v 1.3 :) I need to rework the filtering so it happens prior to the display loop.

**Comment by duplaja** [comment]
Currently, the default to pull is 4.. this is how many to store, not how many to display. I do want to bump this number up a bit. show_x_more should control how many to show. So the idea is maybe you pull 50, and show 5... so it'll display the most recent 5 that match all of your filters, from the 50 pulled, and show those.

Could use some examples in the readme

**Comment by jonathanbossenger** [comment]
Sound good, if you code it I'd be happy to help you to document the functionality. It's a great plugin.

**Comment by duplaja** [comment]
Thanks! It is currently in place! Most of the documentation is in the readme file

**Comment by duplaja** [comment]
Forgot to close this, closing now. In place since Feb
