### ISSUE TITLE
Client profile images 0KB

### ISSUE THREAD

**Issue by tamara-m** [duplaja/codeable-reviews-and-expert-profile#8]
Client profile pics are missing in their reviews. All other data is there, and it's updated as well, just no profile pics other than Codeable's gray placeholder.

Can see PNG files in /codeable-reviews-and-expert-profile/img/profiles/ with file names like medium_2be16f0c20d10a9c9f2f1eabdf7a3511.png

However they are all  0KB.

Will explore some more.

**Comment by duplaja** [comment]
Thank you for the information!

Do you happen to have a live link that I could look at where you are using
this? I'll see what I can find.

**Comment by tamara-m** [comment]
https://magicoders.com/#reviews

It's a bad site, I know...

**Comment by tamara-m** [comment]
Hmmm....

Different page loads images correctly! https://magicoders.com/our-codeable-reviews/ 

But from app.codeable.io S3 bucket, eg https://s3.amazonaws.com/app.codeable.io/avatars/client/73063/medium_2be16f0c20d10a9c9f2f1eabdf7a3511.png

Looking up why shortcode on home page attempts to load these from our domain, that seems to be the issue?

**Comment by duplaja** [comment]
If you set the cache attribute to yes in the shortcode, it attempts to save
and serve them locally. Setting to no loads directly from AWS.

**Comment by duplaja** [comment]
Deleting those 0kb images manually will let you try to download them again
as well. I provided a bit more technical information via Slack.

**Comment by tamara-m** [comment]
Brilliant!

**Comment by tamara-m** [comment]
Thank you, Dan, much appreciated.

**Comment by duplaja** [comment]
You are welcome, let me know if that fixes the issue!

**Comment by tamara-m** [comment]
It did, delete 0KB images, refresh, problem solved.

**Comment by tamara-m** [comment]
Sorry, scratch that, looking on the wrong page.

Images generated again with 0KB after delete and refresh.

Switching cache to no solves this for me, but if you need help troubleshooting the local save, happy to help :)

**Comment by duplaja** [comment]
Closing: Host-side issue, but we were able to get this working by bypassing local cache (cache = no)
